### ISSUE TITLE
Vertical dragging doesn't work

### ISSUE THREAD

**Issue by jgillich** [ne0guille/aurelia-split-panel#3]
Horizontal works fine, but in vertical mode dragging does nothing. Is it possible that you didn't get to fully implement it yet? I briefly looked into the code, no clue how it works. 😄 

My code is pretty much what's in the readme:

```
<div split-panel="vertical: true; sizes: [70, 30]" style="height: 500px">
    <div id="top-pane">
      Top
    </div>
    <div id="bottom-pane">
      Bottom
    </div>
</div>
```

**Comment by ne0guille** [comment]
Hey, thanks for reporting this.

I have a demo application but i was working correctly, nevertheless i submit a new version fixing what i might be causing the issue.
Could you try it again? ill upload the working example later but your code seems fine.

**Comment by jgillich** [comment]
Sorry for being a bit late, I just tried it and can confirm it's working now. Thank you very much!
